apiVersion: v1
kind: Service
metadata:
  namespace: lab23
  name: frontend-lab23
  labels:
    name: frontend-lab23
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-lab23
  type: NodePort